on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 1"
name: Test
env:
  GO111MODULE: "on"
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.11.x, 1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x]
        os: [ubuntu-latest, macos-latest] # windows-latest: can't load package: package .out: malformed module path ".out": leading dot in path element
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test
        run: go test -race -coverprofile=coverage.out .
      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.out
